language: go
dist: focal
go:
- 1.16.x
install:
- if [[ -a .git/shallow ]]; then git fetch --unshallow --tags; fi
cache:
  directories:
  - "/$HOME/docker"
services:
- docker
jobs:
  include:
  - stage: test
    name: Run Go tests
    script:
    - make