on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608" # v4.1.0
        with:
         fetch-depth: 0
         fetch-tags: true
      - uses: "actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491" # v5.0.0
      - name: test
        run: |
          make lint
          make build
          make test
